### ISSUE TITLE
Tools hidden in Chamilo should not be visible in app

### ISSUE THREAD

**Issue by ywarnier** [chamilo/mobile-messaging#7]
As student, enter a course where the "documents" tool is hidden: you can see the tool.
This should not happen. The tools list should only show the tools supported by the app *and* enabled in the course.

**Comment by AngelFQC** [comment]
Added in Chamilo API
https://github.com/chamilo/chamilo-lms/commit/9a09260bd0c67822d5a5d2e9c9d285314d547353

**Comment by AngelFQC** [comment]
Issue resolved in 61ea5d1c9c0eb65c0efd9062adbdca184b6c4fc7 and 552978ccaac414b4336511bd23282b72372e64ee
